version: '3.1'

services:

  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
       - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: contacts-db    